# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("https://app.moviemethod.app/login")
    self.driver.set_window_size(1280, 742)
    self.driver.find_element(By.ID, "input-12").click()
    self.driver.find_element(By.ID, "input-12").send_keys("admin")
    self.driver.find_element(By.ID, "input-15").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".btn--warmPink:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn--warmPink:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Cards").click()
    element = self.driver.find_element(By.LINK_TEXT, "Cards")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.LINK_TEXT, "Suggested Edits")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-profile .nav__link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-dropdown-link:nth-child(4)").click()
  
